server.port=${PORT:8080}
spring.application.name=springboot-usermanagement

spring.datasource.url=jdbc:postgresql://dpg-d7b4u9shg0os73a8nihg-a:5432/user_agqu
spring.datasource.username=user_agqu_user
spring.datasource.password=kXHVVTsv6tnPR1Pk20Bc1fGWDJSUNv2o

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
